name: LilyPond Book CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build LaTeX file
      uses: docker://ykarikos/lilypond-book
      with:
        args: lilypond-book --pdf sliding-6ths.lytex

    - name: Build PDF file
      uses: docker://cristiangreco/pdflatex
      with:
        args: pdflatex sliding-6ths.tex

    - name: Build PDF file with table of contents
      uses: docker://cristiangreco/pdflatex
      with:
        args: pdflatex sliding-6ths.tex

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PDF file
        path: sliding-6ths.pdf
